#!/bin/sh
set -eu

: "${SMITH_API_BASE_URL:=/api}"
: "${SMITH_CHAT_BASE_URL:=/chat}"
: "${SMITH_OPERATOR_TOKEN:=}"
: "${SMITH_OPERATOR_PERMISSIONS:=}"
: "${SMITH_FEATURE_TASKS_ENABLED:=false}"
: "${SMITH_FEATURE_CAPABILITY_ENABLED:=false}"
: "${SMITH_FEATURE_CHAT_ENABLED:=false}"
: "${SMITH_FEATURE_SECRETS_ENABLED:=false}"
: "${SMITH_FEATURE_CAPABILITY_ACCESS:=false}"
: "${SMITH_FEATURE_PROVIDER_CLAUDE_ENABLED:=false}"
: "${SMITH_FEATURE_PROVIDER_GEMINI_ENABLED:=false}"
: "${SMITH_FEATURE_PRD_DIAGNOSTIC_RESOLVE_ENABLED:=false}"
: "${SMITH_SHOW_COMING_SOON_PROVIDERS:=false}"
export SMITH_API_BASE_URL
export SMITH_CHAT_BASE_URL
export SMITH_OPERATOR_TOKEN
export SMITH_OPERATOR_PERMISSIONS
export SMITH_FEATURE_TASKS_ENABLED
export SMITH_FEATURE_CAPABILITY_ENABLED
export SMITH_FEATURE_CHAT_ENABLED
export SMITH_FEATURE_SECRETS_ENABLED
export SMITH_FEATURE_CAPABILITY_ACCESS
export SMITH_FEATURE_PROVIDER_CLAUDE_ENABLED
export SMITH_FEATURE_PROVIDER_GEMINI_ENABLED
export SMITH_FEATURE_PRD_DIAGNOSTIC_RESOLVE_ENABLED
export SMITH_SHOW_COMING_SOON_PROVIDERS

envsubst '${SMITH_API_BASE_URL} ${SMITH_CHAT_BASE_URL} ${SMITH_OPERATOR_TOKEN} ${SMITH_OPERATOR_PERMISSIONS} ${SMITH_FEATURE_TASKS_ENABLED} ${SMITH_FEATURE_CAPABILITY_ENABLED} ${SMITH_FEATURE_CHAT_ENABLED} ${SMITH_FEATURE_SECRETS_ENABLED} ${SMITH_FEATURE_CAPABILITY_ACCESS} ${SMITH_FEATURE_PROVIDER_CLAUDE_ENABLED} ${SMITH_FEATURE_PROVIDER_GEMINI_ENABLED} ${SMITH_FEATURE_PRD_DIAGNOSTIC_RESOLVE_ENABLED} ${SMITH_SHOW_COMING_SOON_PROVIDERS}' < /opt/smith/runtime-config.template.js > /tmp/runtime-config.js
