apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "smith.fullname" . }}-core
  labels:
    {{- include "smith.labels" . | nindent 4 }}
    app.kubernetes.io/component: core
spec:
  replicas: {{ .Values.core.replicaCount }}
  selector:
    matchLabels:
      {{- include "smith.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: core
  template:
    metadata:
      labels:
        {{- include "smith.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: core
    spec:
      serviceAccountName: {{ include "smith.serviceAccountName" (dict "component" "core" "root" .) }}
      containers:
        - name: core
          image: "{{ .Values.core.image.repository }}:{{ .Values.core.image.tag }}"
          imagePullPolicy: {{ .Values.core.image.pullPolicy }}
          env:
            - name: SMITH_ETCD_ENDPOINTS
              value: {{ join "," .Values.etcd.endpoints | quote }}
            {{- with .Values.core.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - containerPort: 8081
              name: metrics
          readinessProbe:
            httpGet:
              path: /readyz
              port: metrics
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics
          resources:
            {{- toYaml .Values.core.resources | nindent 12 }}
