{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "smith.runtimeSecretName" . }}
  labels:
    {{- include "smith.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secrets.keys.gitPat }}: {{ .Values.secrets.managed.gitPat | quote }}
  {{ .Values.secrets.keys.runtimeCredentials }}: {{ .Values.secrets.managed.runtimeCredentials | quote }}
{{- end }}
