{{- range $component := list "core" "api" "console" "chat" }}
{{- if (index $.Values $component).serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "smith.serviceAccountName" (dict "component" $component "root" $) }}
  labels:
    {{- include "smith.labels" $ | nindent 4 }}
---
{{- end }}
{{- end }}
