server {
    listen       3000;
    server_name  _;

    root   /usr/share/nginx/html;
    index  index.html;

    location = /healthz {
        default_type text/plain;
        return 200 'ok';
    }

    location = /readyz {
        default_type text/plain;
        return 200 'ready';
    }

    location = /runtime-config.js {
        default_type application/javascript;
        alias /tmp/runtime-config.js;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
