// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: proto/v1/smith.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoopState int32

const (
	LoopState_LOOP_STATE_UNSPECIFIED LoopState = 0
	LoopState_LOOP_STATE_UNRESOLVED  LoopState = 1
	LoopState_LOOP_STATE_RUNNING     LoopState = 2
	LoopState_LOOP_STATE_SYNCED      LoopState = 3
	LoopState_LOOP_STATE_FLATLINE    LoopState = 4
	LoopState_LOOP_STATE_CANCELLED   LoopState = 5
)

// Enum value maps for LoopState.
var (
	LoopState_name = map[int32]string{
		0: "LOOP_STATE_UNSPECIFIED",
		1: "LOOP_STATE_UNRESOLVED",
		2: "LOOP_STATE_RUNNING",
		3: "LOOP_STATE_SYNCED",
		4: "LOOP_STATE_FLATLINE",
		5: "LOOP_STATE_CANCELLED",
	}
	LoopState_value = map[string]int32{
		"LOOP_STATE_UNSPECIFIED": 0,
		"LOOP_STATE_UNRESOLVED":  1,
		"LOOP_STATE_RUNNING":     2,
		"LOOP_STATE_SYNCED":      3,
		"LOOP_STATE_FLATLINE":    4,
		"LOOP_STATE_CANCELLED":   5,
	}
)

func (x LoopState) Enum() *LoopState {
	p := new(LoopState)
	*p = x
	return p
}

func (x LoopState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoopState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v1_smith_proto_enumTypes[0].Descriptor()
}

func (LoopState) Type() protoreflect.EnumType {
	return &file_proto_v1_smith_proto_enumTypes[0]
}

func (x LoopState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoopState.Descriptor instead.
func (LoopState) EnumDescriptor() ([]byte, []int) {
	return file_proto_v1_smith_proto_rawDescGZIP(), []int{0}
}

type MiseEnvironment struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ToolVersionsFile string                 `protobuf:"bytes,1,opt,name=tool_versions_file,json=toolVersionsFile,proto3" json:"tool_versions_file,omitempty"`
	Tools            map[string]string      `protobuf:"bytes,2,rep,name=tools,proto3" json:"tools,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MiseEnvironment) Reset() {
	*x = MiseEnvironment{}
	mi := &file_proto_v1_smith_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MiseEnvironment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiseEnvironment) ProtoMessage() {}

func (x *MiseEnvironment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_smith_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiseEnvironment.ProtoReflect.Descriptor instead.
func (*MiseEnvironment) Descriptor() ([]byte, []int) {
	return file_proto_v1_smith_proto_rawDescGZIP(), []int{0}
}

func (x *MiseEnvironment) GetToolVersionsFile() string {
	if x != nil {
		return x.ToolVersionsFile
	}
	return ""
}

func (x *MiseEnvironment) GetTools() map[string]string {
	if x != nil {
		return x.Tools
	}
	return nil
}

type ContainerImageProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           string                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	PullPolicy    string                 `protobuf:"bytes,2,opt,name=pull_policy,json=pullPolicy,proto3" json:"pull_policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerImageProfile) Reset() {
	*x = ContainerImageProfile{}
	mi := &file_proto_v1_smith_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerImageProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerImageProfile) ProtoMessage() {}

func (x *ContainerImageProfile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_smith_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerImageProfile.ProtoReflect.Descriptor instead.
func (*ContainerImageProfile) Descriptor() ([]byte, []int) {
	return file_proto_v1_smith_proto_rawDescGZIP(), []int{1}
}

func (x *ContainerImageProfile) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *ContainerImageProfile) GetPullPolicy() string {
	if x != nil {
		return x.PullPolicy
	}
	return ""
}

type DockerfileProfile struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ContextDir     string                 `protobuf:"bytes,1,opt,name=context_dir,json=contextDir,proto3" json:"context_dir,omitempty"`
	DockerfilePath string                 `protobuf:"bytes,2,opt,name=dockerfile_path,json=dockerfilePath,proto3" json:"dockerfile_path,omitempty"`
	Target         string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	BuildArgs      map[string]string      `protobuf:"bytes,4,rep,name=build_args,json=buildArgs,proto3" json:"build_args,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DockerfileProfile) Reset() {
	*x = DockerfileProfile{}
	mi := &file_proto_v1_smith_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DockerfileProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerfileProfile) ProtoMessage() {}

func (x *DockerfileProfile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_smith_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerfileProfile.ProtoReflect.Descriptor instead.
func (*DockerfileProfile) Descriptor() ([]byte, []int) {
	return file_proto_v1_smith_proto_rawDescGZIP(), []int{2}
}

func (x *DockerfileProfile) GetContextDir() string {
	if x != nil {
		return x.ContextDir
	}
	return ""
}

func (x *DockerfileProfile) GetDockerfilePath() string {
	if x != nil {
		return x.DockerfilePath
	}
	return ""
}

func (x *DockerfileProfile) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *DockerfileProfile) GetBuildArgs() map[string]string {
	if x != nil {
		return x.BuildArgs
	}
	return nil
}

type LoopEnvironment struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Preset         string                 `protobuf:"bytes,1,opt,name=preset,proto3" json:"preset,omitempty"`
	Mise           *MiseEnvironment       `protobuf:"bytes,2,opt,name=mise,proto3" json:"mise,omitempty"`
	ContainerImage *ContainerImageProfile `protobuf:"bytes,3,opt,name=container_image,json=containerImage,proto3" json:"container_image,omitempty"`
	Dockerfile     *DockerfileProfile     `protobuf:"bytes,4,opt,name=dockerfile,proto3" json:"dockerfile,omitempty"`
	Env            map[string]string      `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ResolvedMode   string                 `protobuf:"bytes,6,opt,name=resolved_mode,json=resolvedMode,proto3" json:"resolved_mode,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LoopEnvironment) Reset() {
	*x = LoopEnvironment{}
	mi := &file_proto_v1_smith_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoopEnvironment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoopEnvironment) ProtoMessage() {}

func (x *LoopEnvironment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_smith_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoopEnvironment.ProtoReflect.Descriptor instead.
func (*LoopEnvironment) Descriptor() ([]byte, []int) {
	return file_proto_v1_smith_proto_rawDescGZIP(), []int{3}
}

func (x *LoopEnvironment) GetPreset() string {
	if x != nil {
		return x.Preset
	}
	return ""
}

func (x *LoopEnvironment) GetMise() *MiseEnvironment {
	if x != nil {
		return x.Mise
	}
	return nil
}

func (x *LoopEnvironment) GetContainerImage() *ContainerImageProfile {
	if x != nil {
		return x.ContainerImage
	}
	return nil
}

func (x *LoopEnvironment) GetDockerfile() *DockerfileProfile {
	if x != nil {
		return x.Dockerfile
	}
	return nil
}

func (x *LoopEnvironment) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *LoopEnvironment) GetResolvedMode() string {
	if x != nil {
		return x.ResolvedMode
	}
	return ""
}

type LoopSkillMount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	MountPath     string                 `protobuf:"bytes,4,opt,name=mount_path,json=mountPath,proto3" json:"mount_path,omitempty"`
	ReadOnly      bool                   `protobuf:"varint,5,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	Config        map[string]string      `protobuf:"bytes,6,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoopSkillMount) Reset() {
	*x = LoopSkillMount{}
	mi := &file_proto_v1_smith_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoopSkillMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoopSkillMount) ProtoMessage() {}

func (x *LoopSkillMount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_smith_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoopSkillMount.ProtoReflect.Descriptor instead.
func (*LoopSkillMount) Descriptor() ([]byte, []int) {
	return file_proto_v1_smith_proto_rawDescGZIP(), []int{4}
}

func (x *LoopSkillMount) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LoopSkillMount) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LoopSkillMount) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *LoopSkillMount) GetMountPath() string {
	if x != nil {
		return x.MountPath
	}
	return ""
}

func (x *LoopSkillMount) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *LoopSkillMount) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type LoopPolicy struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	MaxAttempts         int32                  `protobuf:"varint,1,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	BackoffInitialNanos int64                  `protobuf:"varint,2,opt,name=backoff_initial_nanos,json=backoffInitialNanos,proto3" json:"backoff_initial_nanos,omitempty"`
	BackoffMaxNanos     int64                  `protobuf:"varint,3,opt,name=backoff_max_nanos,json=backoffMaxNanos,proto3" json:"backoff_max_nanos,omitempty"`
	TimeoutNanos        int64                  `protobuf:"varint,4,opt,name=timeout_nanos,json=timeoutNanos,proto3" json:"timeout_nanos,omitempty"`
	TerminateOnError    bool                   `protobuf:"varint,5,opt,name=terminate_on_error,json=terminateOnError,proto3" json:"terminate_on_error,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *LoopPolicy) Reset() {
	*x = LoopPolicy{}
	mi := &file_proto_v1_smith_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoopPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoopPolicy) ProtoMessage() {}

func (x *LoopPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_smith_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoopPolicy.ProtoReflect.Descriptor instead.
func (*LoopPolicy) Descriptor() ([]byte, []int) {
	return file_proto_v1_smith_proto_rawDescGZIP(), []int{5}
}

func (x *LoopPolicy) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *LoopPolicy) GetBackoffInitialNanos() int64 {
	if x != nil {
		return x.BackoffInitialNanos
	}
	return 0
}

func (x *LoopPolicy) GetBackoffMaxNanos() int64 {
	if x != nil {
		return x.BackoffMaxNanos
	}
	return 0
}

func (x *LoopPolicy) GetTimeoutNanos() int64 {
	if x != nil {
		return x.TimeoutNanos
	}
	return 0
}

func (x *LoopPolicy) GetTerminateOnError() bool {
	if x != nil {
		return x.TerminateOnError
	}
	return false
}

type Anomaly struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	SourceType    string                 `protobuf:"bytes,4,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	SourceRef     string                 `protobuf:"bytes,5,opt,name=source_ref,json=sourceRef,proto3" json:"source_ref,omitempty"`
	ProviderId    string                 `protobuf:"bytes,6,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	Model         string                 `protobuf:"bytes,7,opt,name=model,proto3" json:"model,omitempty"`
	Environment   *LoopEnvironment       `protobuf:"bytes,8,opt,name=environment,proto3" json:"environment,omitempty"`
	Skills        []*LoopSkillMount      `protobuf:"bytes,9,rep,name=skills,proto3" json:"skills,omitempty"`
	Policy        *LoopPolicy            `protobuf:"bytes,10,opt,name=policy,proto3" json:"policy,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,11,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CorrelationId string                 `protobuf:"bytes,14,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	SchemaVersion string                 `protobuf:"bytes,15,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Anomaly) Reset() {
	*x = Anomaly{}
	mi := &file_proto_v1_smith_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Anomaly) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Anomaly) ProtoMessage() {}

func (x *Anomaly) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_smith_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Anomaly.ProtoReflect.Descriptor instead.
func (*Anomaly) Descriptor() ([]byte, []int) {
	return file_proto_v1_smith_proto_rawDescGZIP(), []int{6}
}

func (x *Anomaly) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Anomaly) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Anomaly) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Anomaly) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *Anomaly) GetSourceRef() string {
	if x != nil {
		return x.SourceRef
	}
	return ""
}

func (x *Anomaly) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *Anomaly) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Anomaly) GetEnvironment() *LoopEnvironment {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *Anomaly) GetSkills() []*LoopSkillMount {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *Anomaly) GetPolicy() *LoopPolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *Anomaly) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Anomaly) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Anomaly) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Anomaly) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *Anomaly) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

type State struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LoopId           string                 `protobuf:"bytes,1,opt,name=loop_id,json=loopId,proto3" json:"loop_id,omitempty"`
	State            LoopState              `protobuf:"varint,2,opt,name=state,proto3,enum=smith.v1.LoopState" json:"state,omitempty"`
	Attempt          int32                  `protobuf:"varint,3,opt,name=attempt,proto3" json:"attempt,omitempty"`
	Reason           string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	WorkerJobName    string                 `protobuf:"bytes,5,opt,name=worker_job_name,json=workerJobName,proto3" json:"worker_job_name,omitempty"`
	LockHolder       string                 `protobuf:"bytes,6,opt,name=lock_holder,json=lockHolder,proto3" json:"lock_holder,omitempty"`
	ObservedRevision int64                  `protobuf:"varint,7,opt,name=observed_revision,json=observedRevision,proto3" json:"observed_revision,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	LastHeartbeatAt  *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_heartbeat_at,json=lastHeartbeatAt,proto3" json:"last_heartbeat_at,omitempty"`
	CorrelationId    string                 `protobuf:"bytes,10,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	SchemaVersion    string                 `protobuf:"bytes,11,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *State) Reset() {
	*x = State{}
	mi := &file_proto_v1_smith_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_smith_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_proto_v1_smith_proto_rawDescGZIP(), []int{7}
}

func (x *State) GetLoopId() string {
	if x != nil {
		return x.LoopId
	}
	return ""
}

func (x *State) GetState() LoopState {
	if x != nil {
		return x.State
	}
	return LoopState_LOOP_STATE_UNSPECIFIED
}

func (x *State) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *State) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *State) GetWorkerJobName() string {
	if x != nil {
		return x.WorkerJobName
	}
	return ""
}

func (x *State) GetLockHolder() string {
	if x != nil {
		return x.LockHolder
	}
	return ""
}

func (x *State) GetObservedRevision() int64 {
	if x != nil {
		return x.ObservedRevision
	}
	return 0
}

func (x *State) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *State) GetLastHeartbeatAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHeartbeatAt
	}
	return nil
}

func (x *State) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *State) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

type LoopWithRevision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *State                 `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	Revision      int64                  `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoopWithRevision) Reset() {
	*x = LoopWithRevision{}
	mi := &file_proto_v1_smith_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoopWithRevision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoopWithRevision) ProtoMessage() {}

func (x *LoopWithRevision) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_smith_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoopWithRevision.ProtoReflect.Descriptor instead.
func (*LoopWithRevision) Descriptor() ([]byte, []int) {
	return file_proto_v1_smith_proto_rawDescGZIP(), []int{8}
}

func (x *LoopWithRevision) GetRecord() *State {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *LoopWithRevision) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type JournalEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoopId        string                 `protobuf:"bytes,1,opt,name=loop_id,json=loopId,proto3" json:"loop_id,omitempty"`
	Sequence      int64                  `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Phase         string                 `protobuf:"bytes,4,opt,name=phase,proto3" json:"phase,omitempty"`
	Level         string                 `protobuf:"bytes,5,opt,name=level,proto3" json:"level,omitempty"`
	ActorType     string                 `protobuf:"bytes,6,opt,name=actor_type,json=actorType,proto3" json:"actor_type,omitempty"`
	ActorId       string                 `protobuf:"bytes,7,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	Message       string                 `protobuf:"bytes,8,opt,name=message,proto3" json:"message,omitempty"`
	Command       string                 `protobuf:"bytes,9,opt,name=command,proto3" json:"command,omitempty"`
	ExitCode      int32                  `protobuf:"varint,10,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,11,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CorrelationId string                 `protobuf:"bytes,12,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	SchemaVersion string                 `protobuf:"bytes,13,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JournalEntry) Reset() {
	*x = JournalEntry{}
	mi := &file_proto_v1_smith_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JournalEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JournalEntry) ProtoMessage() {}

func (x *JournalEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_smith_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JournalEntry.ProtoReflect.Descriptor instead.
func (*JournalEntry) Descriptor() ([]byte, []int) {
	return file_proto_v1_smith_proto_rawDescGZIP(), []int{9}
}

func (x *JournalEntry) GetLoopId() string {
	if x != nil {
		return x.LoopId
	}
	return ""
}

func (x *JournalEntry) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *JournalEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *JournalEntry) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *JournalEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *JournalEntry) GetActorType() string {
	if x != nil {
		return x.ActorType
	}
	return ""
}

func (x *JournalEntry) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *JournalEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JournalEntry) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *JournalEntry) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *JournalEntry) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *JournalEntry) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *JournalEntry) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

type Handoff struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LoopId            string                 `protobuf:"bytes,1,opt,name=loop_id,json=loopId,proto3" json:"loop_id,omitempty"`
	Sequence          int64                  `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Timestamp         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	FinalDiffSummary  string                 `protobuf:"bytes,4,opt,name=final_diff_summary,json=finalDiffSummary,proto3" json:"final_diff_summary,omitempty"`
	ValidationState   string                 `protobuf:"bytes,5,opt,name=validation_state,json=validationState,proto3" json:"validation_state,omitempty"`
	ValidationDetails string                 `protobuf:"bytes,6,opt,name=validation_details,json=validationDetails,proto3" json:"validation_details,omitempty"`
	NextSteps         string                 `protobuf:"bytes,7,opt,name=next_steps,json=nextSteps,proto3" json:"next_steps,omitempty"`
	ArtifactRefs      []string               `protobuf:"bytes,8,rep,name=artifact_refs,json=artifactRefs,proto3" json:"artifact_refs,omitempty"`
	Metadata          map[string]string      `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CorrelationId     string                 `protobuf:"bytes,10,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	SchemaVersion     string                 `protobuf:"bytes,11,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Handoff) Reset() {
	*x = Handoff{}
	mi := &file_proto_v1_smith_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Handoff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Handoff) ProtoMessage() {}

func (x *Handoff) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_smith_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Handoff.ProtoReflect.Descriptor instead.
func (*Handoff) Descriptor() ([]byte, []int) {
	return file_proto_v1_smith_proto_rawDescGZIP(), []int{10}
}

func (x *Handoff) GetLoopId() string {
	if x != nil {
		return x.LoopId
	}
	return ""
}

func (x *Handoff) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Handoff) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Handoff) GetFinalDiffSummary() string {
	if x != nil {
		return x.FinalDiffSummary
	}
	return ""
}

func (x *Handoff) GetValidationState() string {
	if x != nil {
		return x.ValidationState
	}
	return ""
}

func (x *Handoff) GetValidationDetails() string {
	if x != nil {
		return x.ValidationDetails
	}
	return ""
}

func (x *Handoff) GetNextSteps() string {
	if x != nil {
		return x.NextSteps
	}
	return ""
}

func (x *Handoff) GetArtifactRefs() []string {
	if x != nil {
		return x.ArtifactRefs
	}
	return nil
}

func (x *Handoff) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Handoff) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *Handoff) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

type OperatorOverride struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoopId        string                 `protobuf:"bytes,1,opt,name=loop_id,json=loopId,proto3" json:"loop_id,omitempty"`
	Sequence      int64                  `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Actor         string                 `protobuf:"bytes,4,opt,name=actor,proto3" json:"actor,omitempty"`
	Action        string                 `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	TargetState   LoopState              `protobuf:"varint,6,opt,name=target_state,json=targetState,proto3,enum=smith.v1.LoopState" json:"target_state,omitempty"`
	Reason        string                 `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`
	CorrelationId string                 `protobuf:"bytes,8,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	SchemaVersion string                 `protobuf:"bytes,9,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperatorOverride) Reset() {
	*x = OperatorOverride{}
	mi := &file_proto_v1_smith_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatorOverride) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatorOverride) ProtoMessage() {}

func (x *OperatorOverride) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_smith_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatorOverride.ProtoReflect.Descriptor instead.
func (*OperatorOverride) Descriptor() ([]byte, []int) {
	return file_proto_v1_smith_proto_rawDescGZIP(), []int{11}
}

func (x *OperatorOverride) GetLoopId() string {
	if x != nil {
		return x.LoopId
	}
	return ""
}

func (x *OperatorOverride) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *OperatorOverride) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *OperatorOverride) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *OperatorOverride) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *OperatorOverride) GetTargetState() LoopState {
	if x != nil {
		return x.TargetState
	}
	return LoopState_LOOP_STATE_UNSPECIFIED
}

func (x *OperatorOverride) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *OperatorOverride) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *OperatorOverride) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

type AuditRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Actor         string                 `protobuf:"bytes,3,opt,name=actor,proto3" json:"actor,omitempty"`
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	TargetLoopId  string                 `protobuf:"bytes,5,opt,name=target_loop_id,json=targetLoopId,proto3" json:"target_loop_id,omitempty"`
	Reason        string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	CorrelationId string                 `protobuf:"bytes,7,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SchemaVersion string                 `protobuf:"bytes,9,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditRecord) Reset() {
	*x = AuditRecord{}
	mi := &file_proto_v1_smith_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditRecord) ProtoMessage() {}

func (x *AuditRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_smith_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditRecord.ProtoReflect.Descriptor instead.
func (*AuditRecord) Descriptor() ([]byte, []int) {
	return file_proto_v1_smith_proto_rawDescGZIP(), []int{12}
}

func (x *AuditRecord) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *AuditRecord) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *AuditRecord) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *AuditRecord) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditRecord) GetTargetLoopId() string {
	if x != nil {
		return x.TargetLoopId
	}
	return ""
}

func (x *AuditRecord) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AuditRecord) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *AuditRecord) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AuditRecord) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

type ListLoopsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLoopsRequest) Reset() {
	*x = ListLoopsRequest{}
	mi := &file_proto_v1_smith_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLoopsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLoopsRequest) ProtoMessage() {}

func (x *ListLoopsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_smith_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLoopsRequest.ProtoReflect.Descriptor instead.
func (*ListLoopsRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_smith_proto_rawDescGZIP(), []int{13}
}

type ListLoopsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Loops         []*LoopWithRevision    `protobuf:"bytes,1,rep,name=loops,proto3" json:"loops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLoopsResponse) Reset() {
	*x = ListLoopsResponse{}
	mi := &file_proto_v1_smith_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLoopsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLoopsResponse) ProtoMessage() {}

func (x *ListLoopsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_smith_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLoopsResponse.ProtoReflect.Descriptor instead.
func (*ListLoopsResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_smith_proto_rawDescGZIP(), []int{14}
}

func (x *ListLoopsResponse) GetLoops() []*LoopWithRevision {
	if x != nil {
		return x.Loops
	}
	return nil
}

type LoopCreateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LoopId         string                 `protobuf:"bytes,1,opt,name=loop_id,json=loopId,proto3" json:"loop_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Title          string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	SourceType     string                 `protobuf:"bytes,5,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	SourceRef      string                 `protobuf:"bytes,6,opt,name=source_ref,json=sourceRef,proto3" json:"source_ref,omitempty"`
	ProviderId     string                 `protobuf:"bytes,7,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	Model          string                 `protobuf:"bytes,8,opt,name=model,proto3" json:"model,omitempty"`
	CorrelationId  string                 `protobuf:"bytes,9,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Environment    *LoopEnvironment       `protobuf:"bytes,11,opt,name=environment,proto3" json:"environment,omitempty"`
	Skills         []*LoopSkillMount      `protobuf:"bytes,12,rep,name=skills,proto3" json:"skills,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LoopCreateRequest) Reset() {
	*x = LoopCreateRequest{}
	mi := &file_proto_v1_smith_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoopCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoopCreateRequest) ProtoMessage() {}

func (x *LoopCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_smith_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoopCreateRequest.ProtoReflect.Descriptor instead.
func (*LoopCreateRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_smith_proto_rawDescGZIP(), []int{15}
}

func (x *LoopCreateRequest) GetLoopId() string {
	if x != nil {
		return x.LoopId
	}
	return ""
}

func (x *LoopCreateRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *LoopCreateRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *LoopCreateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *LoopCreateRequest) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *LoopCreateRequest) GetSourceRef() string {
	if x != nil {
		return x.SourceRef
	}
	return ""
}

func (x *LoopCreateRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *LoopCreateRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *LoopCreateRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *LoopCreateRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *LoopCreateRequest) GetEnvironment() *LoopEnvironment {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *LoopCreateRequest) GetSkills() []*LoopSkillMount {
	if x != nil {
		return x.Skills
	}
	return nil
}

type LoopCreateResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoopId        string                 `protobuf:"bytes,1,opt,name=loop_id,json=loopId,proto3" json:"loop_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Created       bool                   `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Environment   *LoopEnvironment       `protobuf:"bytes,5,opt,name=environment,proto3" json:"environment,omitempty"`
	Skills        []*LoopSkillMount      `protobuf:"bytes,6,rep,name=skills,proto3" json:"skills,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoopCreateResult) Reset() {
	*x = LoopCreateResult{}
	mi := &file_proto_v1_smith_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoopCreateResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoopCreateResult) ProtoMessage() {}

func (x *LoopCreateResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_smith_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoopCreateResult.ProtoReflect.Descriptor instead.
func (*LoopCreateResult) Descriptor() ([]byte, []int) {
	return file_proto_v1_smith_proto_rawDescGZIP(), []int{16}
}

func (x *LoopCreateResult) GetLoopId() string {
	if x != nil {
		return x.LoopId
	}
	return ""
}

func (x *LoopCreateResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LoopCreateResult) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

func (x *LoopCreateResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoopCreateResult) GetEnvironment() *LoopEnvironment {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *LoopCreateResult) GetSkills() []*LoopSkillMount {
	if x != nil {
		return x.Skills
	}
	return nil
}

type GetLoopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoopId        string                 `protobuf:"bytes,1,opt,name=loop_id,json=loopId,proto3" json:"loop_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoopRequest) Reset() {
	*x = GetLoopRequest{}
	mi := &file_proto_v1_smith_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoopRequest) ProtoMessage() {}

func (x *GetLoopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_smith_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoopRequest.ProtoReflect.Descriptor instead.
func (*GetLoopRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_smith_proto_rawDescGZIP(), []int{17}
}

func (x *GetLoopRequest) GetLoopId() string {
	if x != nil {
		return x.LoopId
	}
	return ""
}

type LoopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *State                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Anomaly       *Anomaly               `protobuf:"bytes,2,opt,name=anomaly,proto3" json:"anomaly,omitempty"`
	Environment   *LoopEnvironment       `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoopResponse) Reset() {
	*x = LoopResponse{}
	mi := &file_proto_v1_smith_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoopResponse) ProtoMessage() {}

func (x *LoopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_smith_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoopResponse.ProtoReflect.Descriptor instead.
func (*LoopResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_smith_proto_rawDescGZIP(), []int{18}
}

func (x *LoopResponse) GetState() *State {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *LoopResponse) GetAnomaly() *Anomaly {
	if x != nil {
		return x.Anomaly
	}
	return nil
}

func (x *LoopResponse) GetEnvironment() *LoopEnvironment {
	if x != nil {
		return x.Environment
	}
	return nil
}

type LoopDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoopId        string                 `protobuf:"bytes,1,opt,name=loop_id,json=loopId,proto3" json:"loop_id,omitempty"`
	Actor         string                 `protobuf:"bytes,2,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoopDeleteRequest) Reset() {
	*x = LoopDeleteRequest{}
	mi := &file_proto_v1_smith_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoopDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoopDeleteRequest) ProtoMessage() {}

func (x *LoopDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_smith_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoopDeleteRequest.ProtoReflect.Descriptor instead.
func (*LoopDeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_smith_proto_rawDescGZIP(), []int{19}
}

func (x *LoopDeleteRequest) GetLoopId() string {
	if x != nil {
		return x.LoopId
	}
	return ""
}

func (x *LoopDeleteRequest) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

type DeleteLoopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoopId        string                 `protobuf:"bytes,1,opt,name=loop_id,json=loopId,proto3" json:"loop_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Actor         string                 `protobuf:"bytes,3,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLoopResponse) Reset() {
	*x = DeleteLoopResponse{}
	mi := &file_proto_v1_smith_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLoopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLoopResponse) ProtoMessage() {}

func (x *DeleteLoopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_smith_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLoopResponse.ProtoReflect.Descriptor instead.
func (*DeleteLoopResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_smith_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteLoopResponse) GetLoopId() string {
	if x != nil {
		return x.LoopId
	}
	return ""
}

func (x *DeleteLoopResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeleteLoopResponse) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

type TraceLoopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoopId        string                 `protobuf:"bytes,1,opt,name=loop_id,json=loopId,proto3" json:"loop_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceLoopRequest) Reset() {
	*x = TraceLoopRequest{}
	mi := &file_proto_v1_smith_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceLoopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceLoopRequest) ProtoMessage() {}

func (x *TraceLoopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_smith_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceLoopRequest.ProtoReflect.Descriptor instead.
func (*TraceLoopRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_smith_proto_rawDescGZIP(), []int{21}
}

func (x *TraceLoopRequest) GetLoopId() string {
	if x != nil {
		return x.LoopId
	}
	return ""
}

type LoopTraceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoopId        string                 `protobuf:"bytes,1,opt,name=loop_id,json=loopId,proto3" json:"loop_id,omitempty"`
	State         *State                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Anomaly       *Anomaly               `protobuf:"bytes,3,opt,name=anomaly,proto3" json:"anomaly,omitempty"`
	Environment   *LoopEnvironment       `protobuf:"bytes,4,opt,name=environment,proto3" json:"environment,omitempty"`
	Journal       []*JournalEntry        `protobuf:"bytes,5,rep,name=journal,proto3" json:"journal,omitempty"`
	Handoffs      []*Handoff             `protobuf:"bytes,6,rep,name=handoffs,proto3" json:"handoffs,omitempty"`
	Overrides     []*OperatorOverride    `protobuf:"bytes,7,rep,name=overrides,proto3" json:"overrides,omitempty"`
	Audit         []*AuditRecord         `protobuf:"bytes,8,rep,name=audit,proto3" json:"audit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoopTraceResponse) Reset() {
	*x = LoopTraceResponse{}
	mi := &file_proto_v1_smith_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoopTraceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoopTraceResponse) ProtoMessage() {}

func (x *LoopTraceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_smith_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoopTraceResponse.ProtoReflect.Descriptor instead.
func (*LoopTraceResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_smith_proto_rawDescGZIP(), []int{22}
}

func (x *LoopTraceResponse) GetLoopId() string {
	if x != nil {
		return x.LoopId
	}
	return ""
}

func (x *LoopTraceResponse) GetState() *State {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *LoopTraceResponse) GetAnomaly() *Anomaly {
	if x != nil {
		return x.Anomaly
	}
	return nil
}

func (x *LoopTraceResponse) GetEnvironment() *LoopEnvironment {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *LoopTraceResponse) GetJournal() []*JournalEntry {
	if x != nil {
		return x.Journal
	}
	return nil
}

func (x *LoopTraceResponse) GetHandoffs() []*Handoff {
	if x != nil {
		return x.Handoffs
	}
	return nil
}

func (x *LoopTraceResponse) GetOverrides() []*OperatorOverride {
	if x != nil {
		return x.Overrides
	}
	return nil
}

func (x *LoopTraceResponse) GetAudit() []*AuditRecord {
	if x != nil {
		return x.Audit
	}
	return nil
}

type GetJournalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoopId        string                 `protobuf:"bytes,1,opt,name=loop_id,json=loopId,proto3" json:"loop_id,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJournalRequest) Reset() {
	*x = GetJournalRequest{}
	mi := &file_proto_v1_smith_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJournalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJournalRequest) ProtoMessage() {}

func (x *GetJournalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_smith_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJournalRequest.ProtoReflect.Descriptor instead.
func (*GetJournalRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_smith_proto_rawDescGZIP(), []int{23}
}

func (x *GetJournalRequest) GetLoopId() string {
	if x != nil {
		return x.LoopId
	}
	return ""
}

func (x *GetJournalRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetJournalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*JournalEntry        `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJournalResponse) Reset() {
	*x = GetJournalResponse{}
	mi := &file_proto_v1_smith_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJournalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJournalResponse) ProtoMessage() {}

func (x *GetJournalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_smith_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJournalResponse.ProtoReflect.Descriptor instead.
func (*GetJournalResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_smith_proto_rawDescGZIP(), []int{24}
}

func (x *GetJournalResponse) GetEntries() []*JournalEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type OverrideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoopId        string                 `protobuf:"bytes,1,opt,name=loop_id,json=loopId,proto3" json:"loop_id,omitempty"`
	TargetState   LoopState              `protobuf:"varint,2,opt,name=target_state,json=targetState,proto3,enum=smith.v1.LoopState" json:"target_state,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Actor         string                 `protobuf:"bytes,4,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OverrideRequest) Reset() {
	*x = OverrideRequest{}
	mi := &file_proto_v1_smith_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverrideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverrideRequest) ProtoMessage() {}

func (x *OverrideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_smith_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverrideRequest.ProtoReflect.Descriptor instead.
func (*OverrideRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_smith_proto_rawDescGZIP(), []int{25}
}

func (x *OverrideRequest) GetLoopId() string {
	if x != nil {
		return x.LoopId
	}
	return ""
}

func (x *OverrideRequest) GetTargetState() LoopState {
	if x != nil {
		return x.TargetState
	}
	return LoopState_LOOP_STATE_UNSPECIFIED
}

func (x *OverrideRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *OverrideRequest) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

type OverrideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoopId        string                 `protobuf:"bytes,1,opt,name=loop_id,json=loopId,proto3" json:"loop_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	State         *State                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Revision      int64                  `protobuf:"varint,4,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OverrideResponse) Reset() {
	*x = OverrideResponse{}
	mi := &file_proto_v1_smith_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverrideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverrideResponse) ProtoMessage() {}

func (x *OverrideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_smith_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverrideResponse.ProtoReflect.Descriptor instead.
func (*OverrideResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_smith_proto_rawDescGZIP(), []int{26}
}

func (x *OverrideResponse) GetLoopId() string {
	if x != nil {
		return x.LoopId
	}
	return ""
}

func (x *OverrideResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OverrideResponse) GetState() *State {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *OverrideResponse) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

var File_proto_v1_smith_proto protoreflect.FileDescriptor

const file_proto_v1_smith_proto_rawDesc = "" +
	"\n" +
	"\x14proto/v1/smith.proto\x12\bsmith.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb5\x01\n" +
	"\x0fMiseEnvironment\x12,\n" +
	"\x12tool_versions_file\x18\x01 \x01(\tR\x10toolVersionsFile\x12:\n" +
	"\x05tools\x18\x02 \x03(\v2$.smith.v1.MiseEnvironment.ToolsEntryR\x05tools\x1a8\n" +
	"\n" +
	"ToolsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"J\n" +
	"\x15ContainerImageProfile\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\x12\x1f\n" +
	"\vpull_policy\x18\x02 \x01(\tR\n" +
	"pullPolicy\"\xfe\x01\n" +
	"\x11DockerfileProfile\x12\x1f\n" +
	"\vcontext_dir\x18\x01 \x01(\tR\n" +
	"contextDir\x12'\n" +
	"\x0fdockerfile_path\x18\x02 \x01(\tR\x0edockerfilePath\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12I\n" +
	"\n" +
	"build_args\x18\x04 \x03(\v2*.smith.v1.DockerfileProfile.BuildArgsEntryR\tbuildArgs\x1a<\n" +
	"\x0eBuildArgsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf2\x02\n" +
	"\x0fLoopEnvironment\x12\x16\n" +
	"\x06preset\x18\x01 \x01(\tR\x06preset\x12-\n" +
	"\x04mise\x18\x02 \x01(\v2\x19.smith.v1.MiseEnvironmentR\x04mise\x12H\n" +
	"\x0fcontainer_image\x18\x03 \x01(\v2\x1f.smith.v1.ContainerImageProfileR\x0econtainerImage\x12;\n" +
	"\n" +
	"dockerfile\x18\x04 \x01(\v2\x1b.smith.v1.DockerfileProfileR\n" +
	"dockerfile\x124\n" +
	"\x03env\x18\x05 \x03(\v2\".smith.v1.LoopEnvironment.EnvEntryR\x03env\x12#\n" +
	"\rresolved_mode\x18\x06 \x01(\tR\fresolvedMode\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8b\x02\n" +
	"\x0eLoopSkillMount\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"mount_path\x18\x04 \x01(\tR\tmountPath\x12\x1b\n" +
	"\tread_only\x18\x05 \x01(\bR\breadOnly\x12<\n" +
	"\x06config\x18\x06 \x03(\v2$.smith.v1.LoopSkillMount.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe2\x01\n" +
	"\n" +
	"LoopPolicy\x12!\n" +
	"\fmax_attempts\x18\x01 \x01(\x05R\vmaxAttempts\x122\n" +
	"\x15backoff_initial_nanos\x18\x02 \x01(\x03R\x13backoffInitialNanos\x12*\n" +
	"\x11backoff_max_nanos\x18\x03 \x01(\x03R\x0fbackoffMaxNanos\x12#\n" +
	"\rtimeout_nanos\x18\x04 \x01(\x03R\ftimeoutNanos\x12,\n" +
	"\x12terminate_on_error\x18\x05 \x01(\bR\x10terminateOnError\"\xa3\x05\n" +
	"\aAnomaly\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vsource_type\x18\x04 \x01(\tR\n" +
	"sourceType\x12\x1d\n" +
	"\n" +
	"source_ref\x18\x05 \x01(\tR\tsourceRef\x12\x1f\n" +
	"\vprovider_id\x18\x06 \x01(\tR\n" +
	"providerId\x12\x14\n" +
	"\x05model\x18\a \x01(\tR\x05model\x12;\n" +
	"\venvironment\x18\b \x01(\v2\x19.smith.v1.LoopEnvironmentR\venvironment\x120\n" +
	"\x06skills\x18\t \x03(\v2\x18.smith.v1.LoopSkillMountR\x06skills\x12,\n" +
	"\x06policy\x18\n" +
	" \x01(\v2\x14.smith.v1.LoopPolicyR\x06policy\x12;\n" +
	"\bmetadata\x18\v \x03(\v2\x1f.smith.v1.Anomaly.MetadataEntryR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12%\n" +
	"\x0ecorrelation_id\x18\x0e \x01(\tR\rcorrelationId\x12%\n" +
	"\x0eschema_version\x18\x0f \x01(\tR\rschemaVersion\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc4\x03\n" +
	"\x05State\x12\x17\n" +
	"\aloop_id\x18\x01 \x01(\tR\x06loopId\x12)\n" +
	"\x05state\x18\x02 \x01(\x0e2\x13.smith.v1.LoopStateR\x05state\x12\x18\n" +
	"\aattempt\x18\x03 \x01(\x05R\aattempt\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12&\n" +
	"\x0fworker_job_name\x18\x05 \x01(\tR\rworkerJobName\x12\x1f\n" +
	"\vlock_holder\x18\x06 \x01(\tR\n" +
	"lockHolder\x12+\n" +
	"\x11observed_revision\x18\a \x01(\x03R\x10observedRevision\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12F\n" +
	"\x11last_heartbeat_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x0flastHeartbeatAt\x12%\n" +
	"\x0ecorrelation_id\x18\n" +
	" \x01(\tR\rcorrelationId\x12%\n" +
	"\x0eschema_version\x18\v \x01(\tR\rschemaVersion\"W\n" +
	"\x10LoopWithRevision\x12'\n" +
	"\x06record\x18\x01 \x01(\v2\x0f.smith.v1.StateR\x06record\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x03R\brevision\"\x81\x04\n" +
	"\fJournalEntry\x12\x17\n" +
	"\aloop_id\x18\x01 \x01(\tR\x06loopId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x03R\bsequence\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x14\n" +
	"\x05phase\x18\x04 \x01(\tR\x05phase\x12\x14\n" +
	"\x05level\x18\x05 \x01(\tR\x05level\x12\x1d\n" +
	"\n" +
	"actor_type\x18\x06 \x01(\tR\tactorType\x12\x19\n" +
	"\bactor_id\x18\a \x01(\tR\aactorId\x12\x18\n" +
	"\amessage\x18\b \x01(\tR\amessage\x12\x18\n" +
	"\acommand\x18\t \x01(\tR\acommand\x12\x1b\n" +
	"\texit_code\x18\n" +
	" \x01(\x05R\bexitCode\x12@\n" +
	"\bmetadata\x18\v \x03(\v2$.smith.v1.JournalEntry.MetadataEntryR\bmetadata\x12%\n" +
	"\x0ecorrelation_id\x18\f \x01(\tR\rcorrelationId\x12%\n" +
	"\x0eschema_version\x18\r \x01(\tR\rschemaVersion\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8c\x04\n" +
	"\aHandoff\x12\x17\n" +
	"\aloop_id\x18\x01 \x01(\tR\x06loopId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x03R\bsequence\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12,\n" +
	"\x12final_diff_summary\x18\x04 \x01(\tR\x10finalDiffSummary\x12)\n" +
	"\x10validation_state\x18\x05 \x01(\tR\x0fvalidationState\x12-\n" +
	"\x12validation_details\x18\x06 \x01(\tR\x11validationDetails\x12\x1d\n" +
	"\n" +
	"next_steps\x18\a \x01(\tR\tnextSteps\x12#\n" +
	"\rartifact_refs\x18\b \x03(\tR\fartifactRefs\x12;\n" +
	"\bmetadata\x18\t \x03(\v2\x1f.smith.v1.Handoff.MetadataEntryR\bmetadata\x12%\n" +
	"\x0ecorrelation_id\x18\n" +
	" \x01(\tR\rcorrelationId\x12%\n" +
	"\x0eschema_version\x18\v \x01(\tR\rschemaVersion\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcd\x02\n" +
	"\x10OperatorOverride\x12\x17\n" +
	"\aloop_id\x18\x01 \x01(\tR\x06loopId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x03R\bsequence\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x14\n" +
	"\x05actor\x18\x04 \x01(\tR\x05actor\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action\x126\n" +
	"\ftarget_state\x18\x06 \x01(\x0e2\x13.smith.v1.LoopStateR\vtargetState\x12\x16\n" +
	"\x06reason\x18\a \x01(\tR\x06reason\x12%\n" +
	"\x0ecorrelation_id\x18\b \x01(\tR\rcorrelationId\x12%\n" +
	"\x0eschema_version\x18\t \x01(\tR\rschemaVersion\"\x9a\x03\n" +
	"\vAuditRecord\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x14\n" +
	"\x05actor\x18\x03 \x01(\tR\x05actor\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12$\n" +
	"\x0etarget_loop_id\x18\x05 \x01(\tR\ftargetLoopId\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\x12%\n" +
	"\x0ecorrelation_id\x18\a \x01(\tR\rcorrelationId\x12?\n" +
	"\bmetadata\x18\b \x03(\v2#.smith.v1.AuditRecord.MetadataEntryR\bmetadata\x12%\n" +
	"\x0eschema_version\x18\t \x01(\tR\rschemaVersion\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x12\n" +
	"\x10ListLoopsRequest\"E\n" +
	"\x11ListLoopsResponse\x120\n" +
	"\x05loops\x18\x01 \x03(\v2\x1a.smith.v1.LoopWithRevisionR\x05loops\"\x9e\x04\n" +
	"\x11LoopCreateRequest\x12\x17\n" +
	"\aloop_id\x18\x01 \x01(\tR\x06loopId\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1f\n" +
	"\vsource_type\x18\x05 \x01(\tR\n" +
	"sourceType\x12\x1d\n" +
	"\n" +
	"source_ref\x18\x06 \x01(\tR\tsourceRef\x12\x1f\n" +
	"\vprovider_id\x18\a \x01(\tR\n" +
	"providerId\x12\x14\n" +
	"\x05model\x18\b \x01(\tR\x05model\x12%\n" +
	"\x0ecorrelation_id\x18\t \x01(\tR\rcorrelationId\x12E\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2).smith.v1.LoopCreateRequest.MetadataEntryR\bmetadata\x12;\n" +
	"\venvironment\x18\v \x01(\v2\x19.smith.v1.LoopEnvironmentR\venvironment\x120\n" +
	"\x06skills\x18\f \x03(\v2\x18.smith.v1.LoopSkillMountR\x06skills\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe6\x01\n" +
	"\x10LoopCreateResult\x12\x17\n" +
	"\aloop_id\x18\x01 \x01(\tR\x06loopId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\acreated\x18\x03 \x01(\bR\acreated\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12;\n" +
	"\venvironment\x18\x05 \x01(\v2\x19.smith.v1.LoopEnvironmentR\venvironment\x120\n" +
	"\x06skills\x18\x06 \x03(\v2\x18.smith.v1.LoopSkillMountR\x06skills\")\n" +
	"\x0eGetLoopRequest\x12\x17\n" +
	"\aloop_id\x18\x01 \x01(\tR\x06loopId\"\x9f\x01\n" +
	"\fLoopResponse\x12%\n" +
	"\x05state\x18\x01 \x01(\v2\x0f.smith.v1.StateR\x05state\x12+\n" +
	"\aanomaly\x18\x02 \x01(\v2\x11.smith.v1.AnomalyR\aanomaly\x12;\n" +
	"\venvironment\x18\x03 \x01(\v2\x19.smith.v1.LoopEnvironmentR\venvironment\"B\n" +
	"\x11LoopDeleteRequest\x12\x17\n" +
	"\aloop_id\x18\x01 \x01(\tR\x06loopId\x12\x14\n" +
	"\x05actor\x18\x02 \x01(\tR\x05actor\"[\n" +
	"\x12DeleteLoopResponse\x12\x17\n" +
	"\aloop_id\x18\x01 \x01(\tR\x06loopId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05actor\x18\x03 \x01(\tR\x05actor\"+\n" +
	"\x10TraceLoopRequest\x12\x17\n" +
	"\aloop_id\x18\x01 \x01(\tR\x06loopId\"\x85\x03\n" +
	"\x11LoopTraceResponse\x12\x17\n" +
	"\aloop_id\x18\x01 \x01(\tR\x06loopId\x12%\n" +
	"\x05state\x18\x02 \x01(\v2\x0f.smith.v1.StateR\x05state\x12+\n" +
	"\aanomaly\x18\x03 \x01(\v2\x11.smith.v1.AnomalyR\aanomaly\x12;\n" +
	"\venvironment\x18\x04 \x01(\v2\x19.smith.v1.LoopEnvironmentR\venvironment\x120\n" +
	"\ajournal\x18\x05 \x03(\v2\x16.smith.v1.JournalEntryR\ajournal\x12-\n" +
	"\bhandoffs\x18\x06 \x03(\v2\x11.smith.v1.HandoffR\bhandoffs\x128\n" +
	"\toverrides\x18\a \x03(\v2\x1a.smith.v1.OperatorOverrideR\toverrides\x12+\n" +
	"\x05audit\x18\b \x03(\v2\x15.smith.v1.AuditRecordR\x05audit\"B\n" +
	"\x11GetJournalRequest\x12\x17\n" +
	"\aloop_id\x18\x01 \x01(\tR\x06loopId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\"F\n" +
	"\x12GetJournalResponse\x120\n" +
	"\aentries\x18\x01 \x03(\v2\x16.smith.v1.JournalEntryR\aentries\"\x90\x01\n" +
	"\x0fOverrideRequest\x12\x17\n" +
	"\aloop_id\x18\x01 \x01(\tR\x06loopId\x126\n" +
	"\ftarget_state\x18\x02 \x01(\x0e2\x13.smith.v1.LoopStateR\vtargetState\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x14\n" +
	"\x05actor\x18\x04 \x01(\tR\x05actor\"\x86\x01\n" +
	"\x10OverrideResponse\x12\x17\n" +
	"\aloop_id\x18\x01 \x01(\tR\x06loopId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12%\n" +
	"\x05state\x18\x03 \x01(\v2\x0f.smith.v1.StateR\x05state\x12\x1a\n" +
	"\brevision\x18\x04 \x01(\x03R\brevision*\xa4\x01\n" +
	"\tLoopState\x12\x1a\n" +
	"\x16LOOP_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15LOOP_STATE_UNRESOLVED\x10\x01\x12\x16\n" +
	"\x12LOOP_STATE_RUNNING\x10\x02\x12\x15\n" +
	"\x11LOOP_STATE_SYNCED\x10\x03\x12\x17\n" +
	"\x13LOOP_STATE_FLATLINE\x10\x04\x12\x18\n" +
	"\x14LOOP_STATE_CANCELLED\x10\x052\xf7\x03\n" +
	"\fSmithService\x12D\n" +
	"\tListLoops\x12\x1a.smith.v1.ListLoopsRequest\x1a\x1b.smith.v1.ListLoopsResponse\x12E\n" +
	"\n" +
	"CreateLoop\x12\x1b.smith.v1.LoopCreateRequest\x1a\x1a.smith.v1.LoopCreateResult\x12;\n" +
	"\aGetLoop\x12\x18.smith.v1.GetLoopRequest\x1a\x16.smith.v1.LoopResponse\x12G\n" +
	"\n" +
	"DeleteLoop\x12\x1b.smith.v1.LoopDeleteRequest\x1a\x1c.smith.v1.DeleteLoopResponse\x12D\n" +
	"\tTraceLoop\x12\x1a.smith.v1.TraceLoopRequest\x1a\x1b.smith.v1.LoopTraceResponse\x12G\n" +
	"\n" +
	"GetJournal\x12\x1b.smith.v1.GetJournalRequest\x1a\x1c.smith.v1.GetJournalResponse\x12E\n" +
	"\fOverrideLoop\x12\x19.smith.v1.OverrideRequest\x1a\x1a.smith.v1.OverrideResponseB\x15Z\x13smith/pkg/api/v1;v1b\x06proto3"

var (
	file_proto_v1_smith_proto_rawDescOnce sync.Once
	file_proto_v1_smith_proto_rawDescData []byte
)

func file_proto_v1_smith_proto_rawDescGZIP() []byte {
	file_proto_v1_smith_proto_rawDescOnce.Do(func() {
		file_proto_v1_smith_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_smith_proto_rawDesc), len(file_proto_v1_smith_proto_rawDesc)))
	})
	return file_proto_v1_smith_proto_rawDescData
}

var file_proto_v1_smith_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_v1_smith_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_proto_v1_smith_proto_goTypes = []any{
	(LoopState)(0),                // 0: smith.v1.LoopState
	(*MiseEnvironment)(nil),       // 1: smith.v1.MiseEnvironment
	(*ContainerImageProfile)(nil), // 2: smith.v1.ContainerImageProfile
	(*DockerfileProfile)(nil),     // 3: smith.v1.DockerfileProfile
	(*LoopEnvironment)(nil),       // 4: smith.v1.LoopEnvironment
	(*LoopSkillMount)(nil),        // 5: smith.v1.LoopSkillMount
	(*LoopPolicy)(nil),            // 6: smith.v1.LoopPolicy
	(*Anomaly)(nil),               // 7: smith.v1.Anomaly
	(*State)(nil),                 // 8: smith.v1.State
	(*LoopWithRevision)(nil),      // 9: smith.v1.LoopWithRevision
	(*JournalEntry)(nil),          // 10: smith.v1.JournalEntry
	(*Handoff)(nil),               // 11: smith.v1.Handoff
	(*OperatorOverride)(nil),      // 12: smith.v1.OperatorOverride
	(*AuditRecord)(nil),           // 13: smith.v1.AuditRecord
	(*ListLoopsRequest)(nil),      // 14: smith.v1.ListLoopsRequest
	(*ListLoopsResponse)(nil),     // 15: smith.v1.ListLoopsResponse
	(*LoopCreateRequest)(nil),     // 16: smith.v1.LoopCreateRequest
	(*LoopCreateResult)(nil),      // 17: smith.v1.LoopCreateResult
	(*GetLoopRequest)(nil),        // 18: smith.v1.GetLoopRequest
	(*LoopResponse)(nil),          // 19: smith.v1.LoopResponse
	(*LoopDeleteRequest)(nil),     // 20: smith.v1.LoopDeleteRequest
	(*DeleteLoopResponse)(nil),    // 21: smith.v1.DeleteLoopResponse
	(*TraceLoopRequest)(nil),      // 22: smith.v1.TraceLoopRequest
	(*LoopTraceResponse)(nil),     // 23: smith.v1.LoopTraceResponse
	(*GetJournalRequest)(nil),     // 24: smith.v1.GetJournalRequest
	(*GetJournalResponse)(nil),    // 25: smith.v1.GetJournalResponse
	(*OverrideRequest)(nil),       // 26: smith.v1.OverrideRequest
	(*OverrideResponse)(nil),      // 27: smith.v1.OverrideResponse
	nil,                           // 28: smith.v1.MiseEnvironment.ToolsEntry
	nil,                           // 29: smith.v1.DockerfileProfile.BuildArgsEntry
	nil,                           // 30: smith.v1.LoopEnvironment.EnvEntry
	nil,                           // 31: smith.v1.LoopSkillMount.ConfigEntry
	nil,                           // 32: smith.v1.Anomaly.MetadataEntry
	nil,                           // 33: smith.v1.JournalEntry.MetadataEntry
	nil,                           // 34: smith.v1.Handoff.MetadataEntry
	nil,                           // 35: smith.v1.AuditRecord.MetadataEntry
	nil,                           // 36: smith.v1.LoopCreateRequest.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 37: google.protobuf.Timestamp
}
var file_proto_v1_smith_proto_depIdxs = []int32{
	28, // 0: smith.v1.MiseEnvironment.tools:type_name -> smith.v1.MiseEnvironment.ToolsEntry
	29, // 1: smith.v1.DockerfileProfile.build_args:type_name -> smith.v1.DockerfileProfile.BuildArgsEntry
	1,  // 2: smith.v1.LoopEnvironment.mise:type_name -> smith.v1.MiseEnvironment
	2,  // 3: smith.v1.LoopEnvironment.container_image:type_name -> smith.v1.ContainerImageProfile
	3,  // 4: smith.v1.LoopEnvironment.dockerfile:type_name -> smith.v1.DockerfileProfile
	30, // 5: smith.v1.LoopEnvironment.env:type_name -> smith.v1.LoopEnvironment.EnvEntry
	31, // 6: smith.v1.LoopSkillMount.config:type_name -> smith.v1.LoopSkillMount.ConfigEntry
	4,  // 7: smith.v1.Anomaly.environment:type_name -> smith.v1.LoopEnvironment
	5,  // 8: smith.v1.Anomaly.skills:type_name -> smith.v1.LoopSkillMount
	6,  // 9: smith.v1.Anomaly.policy:type_name -> smith.v1.LoopPolicy
	32, // 10: smith.v1.Anomaly.metadata:type_name -> smith.v1.Anomaly.MetadataEntry
	37, // 11: smith.v1.Anomaly.created_at:type_name -> google.protobuf.Timestamp
	37, // 12: smith.v1.Anomaly.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 13: smith.v1.State.state:type_name -> smith.v1.LoopState
	37, // 14: smith.v1.State.updated_at:type_name -> google.protobuf.Timestamp
	37, // 15: smith.v1.State.last_heartbeat_at:type_name -> google.protobuf.Timestamp
	8,  // 16: smith.v1.LoopWithRevision.record:type_name -> smith.v1.State
	37, // 17: smith.v1.JournalEntry.timestamp:type_name -> google.protobuf.Timestamp
	33, // 18: smith.v1.JournalEntry.metadata:type_name -> smith.v1.JournalEntry.MetadataEntry
	37, // 19: smith.v1.Handoff.timestamp:type_name -> google.protobuf.Timestamp
	34, // 20: smith.v1.Handoff.metadata:type_name -> smith.v1.Handoff.MetadataEntry
	37, // 21: smith.v1.OperatorOverride.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 22: smith.v1.OperatorOverride.target_state:type_name -> smith.v1.LoopState
	37, // 23: smith.v1.AuditRecord.timestamp:type_name -> google.protobuf.Timestamp
	35, // 24: smith.v1.AuditRecord.metadata:type_name -> smith.v1.AuditRecord.MetadataEntry
	9,  // 25: smith.v1.ListLoopsResponse.loops:type_name -> smith.v1.LoopWithRevision
	36, // 26: smith.v1.LoopCreateRequest.metadata:type_name -> smith.v1.LoopCreateRequest.MetadataEntry
	4,  // 27: smith.v1.LoopCreateRequest.environment:type_name -> smith.v1.LoopEnvironment
	5,  // 28: smith.v1.LoopCreateRequest.skills:type_name -> smith.v1.LoopSkillMount
	4,  // 29: smith.v1.LoopCreateResult.environment:type_name -> smith.v1.LoopEnvironment
	5,  // 30: smith.v1.LoopCreateResult.skills:type_name -> smith.v1.LoopSkillMount
	8,  // 31: smith.v1.LoopResponse.state:type_name -> smith.v1.State
	7,  // 32: smith.v1.LoopResponse.anomaly:type_name -> smith.v1.Anomaly
	4,  // 33: smith.v1.LoopResponse.environment:type_name -> smith.v1.LoopEnvironment
	8,  // 34: smith.v1.LoopTraceResponse.state:type_name -> smith.v1.State
	7,  // 35: smith.v1.LoopTraceResponse.anomaly:type_name -> smith.v1.Anomaly
	4,  // 36: smith.v1.LoopTraceResponse.environment:type_name -> smith.v1.LoopEnvironment
	10, // 37: smith.v1.LoopTraceResponse.journal:type_name -> smith.v1.JournalEntry
	11, // 38: smith.v1.LoopTraceResponse.handoffs:type_name -> smith.v1.Handoff
	12, // 39: smith.v1.LoopTraceResponse.overrides:type_name -> smith.v1.OperatorOverride
	13, // 40: smith.v1.LoopTraceResponse.audit:type_name -> smith.v1.AuditRecord
	10, // 41: smith.v1.GetJournalResponse.entries:type_name -> smith.v1.JournalEntry
	0,  // 42: smith.v1.OverrideRequest.target_state:type_name -> smith.v1.LoopState
	8,  // 43: smith.v1.OverrideResponse.state:type_name -> smith.v1.State
	14, // 44: smith.v1.SmithService.ListLoops:input_type -> smith.v1.ListLoopsRequest
	16, // 45: smith.v1.SmithService.CreateLoop:input_type -> smith.v1.LoopCreateRequest
	18, // 46: smith.v1.SmithService.GetLoop:input_type -> smith.v1.GetLoopRequest
	20, // 47: smith.v1.SmithService.DeleteLoop:input_type -> smith.v1.LoopDeleteRequest
	22, // 48: smith.v1.SmithService.TraceLoop:input_type -> smith.v1.TraceLoopRequest
	24, // 49: smith.v1.SmithService.GetJournal:input_type -> smith.v1.GetJournalRequest
	26, // 50: smith.v1.SmithService.OverrideLoop:input_type -> smith.v1.OverrideRequest
	15, // 51: smith.v1.SmithService.ListLoops:output_type -> smith.v1.ListLoopsResponse
	17, // 52: smith.v1.SmithService.CreateLoop:output_type -> smith.v1.LoopCreateResult
	19, // 53: smith.v1.SmithService.GetLoop:output_type -> smith.v1.LoopResponse
	21, // 54: smith.v1.SmithService.DeleteLoop:output_type -> smith.v1.DeleteLoopResponse
	23, // 55: smith.v1.SmithService.TraceLoop:output_type -> smith.v1.LoopTraceResponse
	25, // 56: smith.v1.SmithService.GetJournal:output_type -> smith.v1.GetJournalResponse
	27, // 57: smith.v1.SmithService.OverrideLoop:output_type -> smith.v1.OverrideResponse
	51, // [51:58] is the sub-list for method output_type
	44, // [44:51] is the sub-list for method input_type
	44, // [44:44] is the sub-list for extension type_name
	44, // [44:44] is the sub-list for extension extendee
	0,  // [0:44] is the sub-list for field type_name
}

func init() { file_proto_v1_smith_proto_init() }
func file_proto_v1_smith_proto_init() {
	if File_proto_v1_smith_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_smith_proto_rawDesc), len(file_proto_v1_smith_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_smith_proto_goTypes,
		DependencyIndexes: file_proto_v1_smith_proto_depIdxs,
		EnumInfos:         file_proto_v1_smith_proto_enumTypes,
		MessageInfos:      file_proto_v1_smith_proto_msgTypes,
	}.Build()
	File_proto_v1_smith_proto = out.File
	file_proto_v1_smith_proto_goTypes = nil
	file_proto_v1_smith_proto_depIdxs = nil
}
