// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.20.3
// source: proto/v1/smith.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SmithService_ListLoops_FullMethodName    = "/smith.v1.SmithService/ListLoops"
	SmithService_CreateLoop_FullMethodName   = "/smith.v1.SmithService/CreateLoop"
	SmithService_GetLoop_FullMethodName      = "/smith.v1.SmithService/GetLoop"
	SmithService_DeleteLoop_FullMethodName   = "/smith.v1.SmithService/DeleteLoop"
	SmithService_TraceLoop_FullMethodName    = "/smith.v1.SmithService/TraceLoop"
	SmithService_GetJournal_FullMethodName   = "/smith.v1.SmithService/GetJournal"
	SmithService_OverrideLoop_FullMethodName = "/smith.v1.SmithService/OverrideLoop"
)

// SmithServiceClient is the client API for SmithService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SmithServiceClient interface {
	ListLoops(ctx context.Context, in *ListLoopsRequest, opts ...grpc.CallOption) (*ListLoopsResponse, error)
	CreateLoop(ctx context.Context, in *LoopCreateRequest, opts ...grpc.CallOption) (*LoopCreateResult, error)
	GetLoop(ctx context.Context, in *GetLoopRequest, opts ...grpc.CallOption) (*LoopResponse, error)
	DeleteLoop(ctx context.Context, in *LoopDeleteRequest, opts ...grpc.CallOption) (*DeleteLoopResponse, error)
	TraceLoop(ctx context.Context, in *TraceLoopRequest, opts ...grpc.CallOption) (*LoopTraceResponse, error)
	GetJournal(ctx context.Context, in *GetJournalRequest, opts ...grpc.CallOption) (*GetJournalResponse, error)
	OverrideLoop(ctx context.Context, in *OverrideRequest, opts ...grpc.CallOption) (*OverrideResponse, error)
}

type smithServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSmithServiceClient(cc grpc.ClientConnInterface) SmithServiceClient {
	return &smithServiceClient{cc}
}

func (c *smithServiceClient) ListLoops(ctx context.Context, in *ListLoopsRequest, opts ...grpc.CallOption) (*ListLoopsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLoopsResponse)
	err := c.cc.Invoke(ctx, SmithService_ListLoops_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smithServiceClient) CreateLoop(ctx context.Context, in *LoopCreateRequest, opts ...grpc.CallOption) (*LoopCreateResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoopCreateResult)
	err := c.cc.Invoke(ctx, SmithService_CreateLoop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smithServiceClient) GetLoop(ctx context.Context, in *GetLoopRequest, opts ...grpc.CallOption) (*LoopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoopResponse)
	err := c.cc.Invoke(ctx, SmithService_GetLoop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smithServiceClient) DeleteLoop(ctx context.Context, in *LoopDeleteRequest, opts ...grpc.CallOption) (*DeleteLoopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteLoopResponse)
	err := c.cc.Invoke(ctx, SmithService_DeleteLoop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smithServiceClient) TraceLoop(ctx context.Context, in *TraceLoopRequest, opts ...grpc.CallOption) (*LoopTraceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoopTraceResponse)
	err := c.cc.Invoke(ctx, SmithService_TraceLoop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smithServiceClient) GetJournal(ctx context.Context, in *GetJournalRequest, opts ...grpc.CallOption) (*GetJournalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJournalResponse)
	err := c.cc.Invoke(ctx, SmithService_GetJournal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smithServiceClient) OverrideLoop(ctx context.Context, in *OverrideRequest, opts ...grpc.CallOption) (*OverrideResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OverrideResponse)
	err := c.cc.Invoke(ctx, SmithService_OverrideLoop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SmithServiceServer is the server API for SmithService service.
// All implementations must embed UnimplementedSmithServiceServer
// for forward compatibility.
type SmithServiceServer interface {
	ListLoops(context.Context, *ListLoopsRequest) (*ListLoopsResponse, error)
	CreateLoop(context.Context, *LoopCreateRequest) (*LoopCreateResult, error)
	GetLoop(context.Context, *GetLoopRequest) (*LoopResponse, error)
	DeleteLoop(context.Context, *LoopDeleteRequest) (*DeleteLoopResponse, error)
	TraceLoop(context.Context, *TraceLoopRequest) (*LoopTraceResponse, error)
	GetJournal(context.Context, *GetJournalRequest) (*GetJournalResponse, error)
	OverrideLoop(context.Context, *OverrideRequest) (*OverrideResponse, error)
	mustEmbedUnimplementedSmithServiceServer()
}

// UnimplementedSmithServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSmithServiceServer struct{}

func (UnimplementedSmithServiceServer) ListLoops(context.Context, *ListLoopsRequest) (*ListLoopsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLoops not implemented")
}
func (UnimplementedSmithServiceServer) CreateLoop(context.Context, *LoopCreateRequest) (*LoopCreateResult, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateLoop not implemented")
}
func (UnimplementedSmithServiceServer) GetLoop(context.Context, *GetLoopRequest) (*LoopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLoop not implemented")
}
func (UnimplementedSmithServiceServer) DeleteLoop(context.Context, *LoopDeleteRequest) (*DeleteLoopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteLoop not implemented")
}
func (UnimplementedSmithServiceServer) TraceLoop(context.Context, *TraceLoopRequest) (*LoopTraceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TraceLoop not implemented")
}
func (UnimplementedSmithServiceServer) GetJournal(context.Context, *GetJournalRequest) (*GetJournalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJournal not implemented")
}
func (UnimplementedSmithServiceServer) OverrideLoop(context.Context, *OverrideRequest) (*OverrideResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OverrideLoop not implemented")
}
func (UnimplementedSmithServiceServer) mustEmbedUnimplementedSmithServiceServer() {}
func (UnimplementedSmithServiceServer) testEmbeddedByValue()                      {}

// UnsafeSmithServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SmithServiceServer will
// result in compilation errors.
type UnsafeSmithServiceServer interface {
	mustEmbedUnimplementedSmithServiceServer()
}

func RegisterSmithServiceServer(s grpc.ServiceRegistrar, srv SmithServiceServer) {
	// If the following call panics, it indicates UnimplementedSmithServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SmithService_ServiceDesc, srv)
}

func _SmithService_ListLoops_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLoopsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmithServiceServer).ListLoops(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmithService_ListLoops_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmithServiceServer).ListLoops(ctx, req.(*ListLoopsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmithService_CreateLoop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoopCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmithServiceServer).CreateLoop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmithService_CreateLoop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmithServiceServer).CreateLoop(ctx, req.(*LoopCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmithService_GetLoop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLoopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmithServiceServer).GetLoop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmithService_GetLoop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmithServiceServer).GetLoop(ctx, req.(*GetLoopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmithService_DeleteLoop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoopDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmithServiceServer).DeleteLoop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmithService_DeleteLoop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmithServiceServer).DeleteLoop(ctx, req.(*LoopDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmithService_TraceLoop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TraceLoopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmithServiceServer).TraceLoop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmithService_TraceLoop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmithServiceServer).TraceLoop(ctx, req.(*TraceLoopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmithService_GetJournal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJournalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmithServiceServer).GetJournal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmithService_GetJournal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmithServiceServer).GetJournal(ctx, req.(*GetJournalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmithService_OverrideLoop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OverrideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmithServiceServer).OverrideLoop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmithService_OverrideLoop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmithServiceServer).OverrideLoop(ctx, req.(*OverrideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SmithService_ServiceDesc is the grpc.ServiceDesc for SmithService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SmithService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "smith.v1.SmithService",
	HandlerType: (*SmithServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListLoops",
			Handler:    _SmithService_ListLoops_Handler,
		},
		{
			MethodName: "CreateLoop",
			Handler:    _SmithService_CreateLoop_Handler,
		},
		{
			MethodName: "GetLoop",
			Handler:    _SmithService_GetLoop_Handler,
		},
		{
			MethodName: "DeleteLoop",
			Handler:    _SmithService_DeleteLoop_Handler,
		},
		{
			MethodName: "TraceLoop",
			Handler:    _SmithService_TraceLoop_Handler,
		},
		{
			MethodName: "GetJournal",
			Handler:    _SmithService_GetJournal_Handler,
		},
		{
			MethodName: "OverrideLoop",
			Handler:    _SmithService_OverrideLoop_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/v1/smith.proto",
}
