package completion

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"sort"
	"strings"
)

type RealGit struct {
	Workspace  string
	Repository string
	Branch     string
	PAT        string
	UserName   string
	UserEmail  string
}

const (
	defaultGitCommitUserName  = "SMITH"
	defaultGitCommitUserEmail = "smith@cromleylabs.com"
)

func (g *RealGit) CommitAndPush(ctx context.Context, loopID string, finalDiff string) (string, error) {
	if g.PAT == "" {
		return "", fmt.Errorf("git push failed: SMITH_GIT_PAT is not set")
	}

	// 1. Configure local git user
	userName := strings.TrimSpace(g.UserName)
	if userName == "" {
		userName = defaultGitCommitUserName
	}
	userEmail := strings.TrimSpace(g.UserEmail)
	if userEmail == "" {
		userEmail = defaultGitCommitUserEmail
	}

	if err := g.run(ctx, "config", "user.name", userName); err != nil {
		return "", err
	}
	if err := g.run(ctx, "config", "user.email", userEmail); err != nil {
		return "", err
	}

	// 2. Add workspace changes while excluding runtime skill mount paths.
	if err := g.run(ctx, gitAddAllArgsExcludingSkillMounts()...); err != nil {
		return "", err
	}

	// 3. Commit
	commitMsg := buildCommitMessage(loopID, finalDiff)
	if err := g.run(ctx, "commit", "-m", commitMsg); err != nil {
		// If there are no changes, commit might fail. We should check if it's actually an error.
		if strings.Contains(err.Error(), "nothing to commit") {
			return g.headSHA(ctx)
		}
		return "", err
	}

	// 4. Push using the PAT in the URL
	// We rewrite the remote URL temporarily to include the PAT for the push
	authURL := g.authURL()
	if err := g.run(ctx, "push", authURL, fmt.Sprintf("HEAD:%s", g.Branch)); err != nil {
		return "", fmt.Errorf("git push failed: %w", err)
	}

	return g.headSHA(ctx)
}

func gitAddAllArgsExcludingSkillMounts() []string {
	args := []string{"add", "-A", "--", "."}
	excludes := map[string]struct{}{
		":(exclude).agents/skills":    {},
		":(exclude).agents/skills/**": {},
		":(exclude).claude/skills":    {},
		":(exclude).claude/skills/**": {},
	}
	for _, spec := range skillMountExcludePathspecs(os.Getenv("SMITH_SKILL_MOUNT_PATHS")) {
		excludes[spec] = struct{}{}
	}
	ordered := make([]string, 0, len(excludes))
	for spec := range excludes {
		ordered = append(ordered, spec)
	}
	sort.Strings(ordered)
	args = append(args, ordered...)
	return args
}

func skillMountExcludePathspecs(rawMountPaths string) []string {
	const workspacePrefix = "/workspace/"
	if strings.TrimSpace(rawMountPaths) == "" {
		return nil
	}
	out := map[string]struct{}{}
	for _, item := range strings.Split(rawMountPaths, ",") {
		mountPath := strings.TrimSpace(item)
		if !strings.HasPrefix(mountPath, workspacePrefix) {
			continue
		}
		rel := strings.Trim(strings.TrimPrefix(mountPath, workspacePrefix), "/")
		if rel == "" {
			continue
		}
		rel = strings.ReplaceAll(rel, "\\", "/")
		out[":(exclude)"+rel] = struct{}{}
		out[":(exclude)"+rel+"/**"] = struct{}{}
	}
	if len(out) == 0 {
		return nil
	}
	ordered := make([]string, 0, len(out))
	for spec := range out {
		ordered = append(ordered, spec)
	}
	sort.Strings(ordered)
	return ordered
}

func buildCommitMessage(loopID, finalDiff string) string {
	summary := "autonomous implementation update"
	details := ""

	trimmed := strings.TrimSpace(finalDiff)
	if trimmed != "" {
		parts := strings.Split(trimmed, "\n")
		first := strings.TrimSpace(parts[0])
		if first != "" {
			summary = collapseCommitLine(first, 72)
		}
		if len(parts) > 1 {
			remaining := strings.TrimSpace(strings.Join(parts[1:], "\n"))
			if remaining != "" {
				details = remaining
			}
		}
	}

	message := fmt.Sprintf("feat(loop): %s\n\nLoop-ID: %s", summary, strings.TrimSpace(loopID))
	if details != "" {
		message += "\n\n" + details
	}
	return message
}

func collapseCommitLine(value string, limit int) string {
	value = strings.Join(strings.Fields(strings.TrimSpace(value)), " ")
	if value == "" {
		return "autonomous implementation update"
	}
	if limit <= 0 || len(value) <= limit {
		return value
	}
	trimmed := strings.TrimSpace(value[:limit])
	if trimmed == "" {
		return value[:limit]
	}
	return trimmed
}

func (g *RealGit) CreatePullRequest(ctx context.Context, loopID string, commitSHA string, title string, body string) (string, error) {
	if title == "" {
		title = "chore(loop): autonomous update for loop " + loopID
	}
	if body == "" {
		body = "This Pull Request was autonomously generated by Smith for loop " + loopID + ".\n\nCommit: " + commitSHA
	}

	cmd := exec.CommandContext(ctx, "gh", "pr", "create", "--title", title, "--body", body, "--head", g.Branch)
	cmd.Dir = g.Workspace
	if g.PAT != "" {
		cmd.Env = append(os.Environ(), "GITHUB_TOKEN="+g.PAT)
	}
	out, err := cmd.CombinedOutput()
	if err != nil {
		// Check if PR already exists
		if strings.Contains(string(out), "already exists") {
			cmdList := exec.CommandContext(ctx, "gh", "pr", "list", "--head", g.Branch, "--json", "url", "-q", ".[0].url")
			cmdList.Dir = g.Workspace
			if g.PAT != "" {
				cmdList.Env = append(os.Environ(), "GITHUB_TOKEN="+g.PAT)
			}
			existing, listErr := cmdList.Output()
			if listErr == nil {
				return strings.TrimSpace(string(existing)), nil
			}
		}
		return "", fmt.Errorf("gh pr create failed: %w (output: %s)", err, string(out))
	}
	return strings.TrimSpace(string(out)), nil
}

func (g *RealGit) Revert(ctx context.Context, loopID string, commitSHA string) error {
	// Revert is used for compensation in the saga.
	// In this implementation, we'll just push a revert commit or force-push back if appropriate.
	// For simplicity and safety in MVP, we'll push a revert.
	if err := g.run(ctx, "revert", "--no-edit", commitSHA); err != nil {
		return err
	}
	authURL := g.authURL()
	return g.run(ctx, "push", authURL, fmt.Sprintf("HEAD:%s", g.Branch))
}

func (g *RealGit) run(ctx context.Context, args ...string) error {
	cmd := exec.CommandContext(ctx, "git", args...)
	cmd.Dir = g.Workspace
	// Strip PAT from logs if it ever ends up there
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("git %s failed: %w (output: %s)", args[0], err, string(output))
	}
	return nil
}

func (g *RealGit) headSHA(ctx context.Context) (string, error) {
	cmd := exec.CommandContext(ctx, "git", "rev-parse", "HEAD")
	cmd.Dir = g.Workspace
	out, err := cmd.Output()
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(string(out)), nil
}

func (g *RealGit) authURL() string {
	repo := g.Repository
	// Basic URL rewrite for GitHub PAT: https://<pat>@github.com/org/repo.git
	if strings.HasPrefix(repo, "https://") {
		return "https://" + g.PAT + "@" + strings.TrimPrefix(repo, "https://")
	}
	return repo
}
